import type { MotorcycleItem, HelmetGearItem, SparePartItem, ActivityLog, StoreLocation } from '../types/inventory';

export const INITIAL_LOCATIONS: StoreLocation[] = [
  {
    id: 'loc-1',
    name: 'Mantash Flagship Hub (Downtown)',
    code: 'MNT-01',
    address: '440 Apex Boulevard, Bay District',
    phone: '+1 (555) 019-8234',
    isPrimary: true
  },
  {
    id: 'loc-2',
    name: 'Mantash North Service & Warehouse',
    code: 'MNT-02',
    address: '128 Industrial Speedway Way',
    phone: '+1 (555) 019-9400'
  },
  {
    id: 'loc-3',
    name: 'Mantash West Coast Outlet',
    code: 'MNT-03',
    address: '89 Coastal Ridge Highway',
    phone: '+1 (555) 019-3321'
  }
];

export const INITIAL_MOTORCYCLES: MotorcycleItem[] = [
  {
    id: 'moto-kw-z500',
    type: 'motorcycle',
    vin: 'JKAZX2500MA089123',
    brand: 'KAWASAKI',
    model: 'Z500',
    year: 2026,
    condition: 'Brand New',
    taxCategory: 'Tax',
    engineCc: 451,
    color: 'Metallic Flat Spark Black',
    mileage: 0,
    costPrice: 5100,
    sellingPrice: 6299,
    status: 'In Stock',
    location: 'Mantash Flagship Hub (Downtown)',
    category: 'Naked',
    createdAt: '2024-03-14T10:00:00Z'
  },
  {
    id: 'moto-kw-z900se',
    type: 'motorcycle',
    vin: 'JKAZX2900SE918234',
    brand: 'KAWASAKI',
    model: 'Z900 SE',
    year: 2026,
    condition: 'Brand New',
    taxCategory: 'Tax',
    engineCc: 948,
    color: 'Metallic Spark Black / Candy Lime Green',
    mileage: 0,
    costPrice: 9400,
    sellingPrice: 11399,
    status: 'In Stock',
    location: 'Mantash Flagship Hub (Downtown)',
    category: 'Naked',
    createdAt: '2024-03-10T14:15:00Z'
  },
  {
    id: 'moto-kw-ninja500',
    type: 'motorcycle',
    vin: 'JKANIN500P8391029',
    brand: 'KAWASAKI',
    model: 'NINJA 500',
    year: 2026,
    condition: 'Brand New',
    taxCategory: 'Tax-Free',
    engineCc: 451,
    color: 'Lime Green / Ebony KRT',
    mileage: 0,
    costPrice: 4700,
    sellingPrice: 5899,
    status: 'In Stock',
    location: 'Mantash Flagship Hub (Downtown)',
    category: 'Sport',
    createdAt: '2024-03-08T11:20:00Z'
  },
  {
    id: 'moto-kw-kle500',
    type: 'motorcycle',
    vin: 'JKAKLE500R9182341',
    brand: 'KAWASAKI',
    model: 'KLE 500',
    year: 2026,
    condition: 'Old / Used',
    taxCategory: 'Tax',
    engineCc: 498,
    color: 'Urban Khaki / Matte Graphite',
    mileage: 2400,
    costPrice: 5800,
    sellingPrice: 7199,
    status: 'In Stock',
    location: 'Mantash North Service & Warehouse',
    category: 'Adventure',
    createdAt: '2024-02-28T09:00:00Z'
  },
  {
    id: 'moto-sym-jetx',
    type: 'motorcycle',
    vin: 'RFGJETX125M889123',
    brand: 'SYM',
    model: 'JET X',
    year: 2026,
    condition: 'Brand New',
    taxCategory: 'Tax',
    engineCc: 150,
    color: 'Sleek Matte Navy Blue',
    mileage: 0,
    costPrice: 2800,
    sellingPrice: 3899,
    status: 'In Stock',
    location: 'Mantash Flagship Hub (Downtown)',
    category: 'Naked',
    createdAt: '2024-02-05T16:45:00Z'
  },
  {
    id: 'moto-sym-cruisym',
    type: 'motorcycle',
    vin: 'RFGCRUISYM300P123',
    brand: 'SYM',
    model: 'CRUISYM',
    year: 2026,
    condition: 'Brand New',
    taxCategory: 'Tax-Free',
    engineCc: 300,
    color: 'Titanium Silver Matte',
    mileage: 0,
    costPrice: 3900,
    sellingPrice: 5199,
    status: 'In Stock',
    location: 'Mantash Flagship Hub (Downtown)',
    category: 'Touring',
    createdAt: '2024-01-20T13:00:00Z'
  },
  {
    id: 'moto-sym-adxtg',
    type: 'motorcycle',
    vin: 'RFGADXTG400P99120',
    brand: 'SYM',
    model: 'ADXTG',
    year: 2026,
    condition: 'Brand New',
    taxCategory: 'Tax-Free',
    engineCc: 400,
    color: 'Alpine White Cross',
    mileage: 0,
    costPrice: 4800,
    sellingPrice: 6299,
    status: 'In Stock',
    location: 'Mantash West Coast Outlet',
    category: 'Adventure',
    createdAt: '2024-01-15T15:10:00Z'
  },
  {
    id: 'moto-sym-shex',
    type: 'motorcycle',
    vin: 'RFGSHEX125P019284',
    brand: 'SYM',
    model: 'SHEX',
    year: 2026,
    condition: 'Brand New',
    taxCategory: 'Tax',
    engineCc: 125,
    color: 'Gloss Carbon Trio Livery',
    mileage: 0,
    costPrice: 2200,
    sellingPrice: 2999,
    status: 'In Stock',
    location: 'Mantash Flagship Hub (Downtown)',
    category: 'Naked',
    createdAt: '2024-01-11T12:00:00Z'
  },
  {
    id: 'moto-bmw-s1000r',
    type: 'motorcycle',
    vin: 'WB10E0203P6B88192',
    brand: 'BMW',
    model: 'S1000R',
    year: 2022,
    condition: 'Old / Used',
    taxCategory: 'Tax-Free',
    engineCc: 999,
    color: 'Hockenheim Silver Metallic',
    mileage: 3840,
    costPrice: 12400,
    sellingPrice: 15495,
    status: 'In Stock',
    location: 'Mantash North Service & Warehouse',
    category: 'Sport',
    createdAt: '2024-01-05T09:00:00Z'
  },
  {
    id: 'moto-yam-jog',
    type: 'motorcycle',
    vin: 'JYARN23E98A019283',
    brand: 'YAMAHA',
    model: 'JOG ARTISTIC SPEC',
    year: 2026,
    condition: 'Old / Used',
    taxCategory: 'Tax',
    engineCc: 50,
    color: 'Racing White / Speedblock Red',
    mileage: 1800,
    costPrice: 1400,
    sellingPrice: 1999,
    status: 'In Stock',
    location: 'Mantash Flagship Hub (Downtown)',
    category: 'Naked',
    createdAt: '2024-01-02T14:15:00Z'
  },
  {
    id: 'moto-ducati-v4s',
    type: 'motorcycle',
    vin: 'JH2SC59038K102941',
    brand: 'DUCATI',
    model: 'PANIGALE V4 S',
    year: 2024,
    condition: 'Brand New',
    taxCategory: 'Tax-Free',
    engineCc: 1103,
    color: 'Rosso Corsa Red',
    mileage: 0,
    costPrice: 26500,
    sellingPrice: 31995,
    status: 'In Stock',
    location: 'Mantash Flagship Hub (Downtown)',
    category: 'Sport',
    createdAt: '2024-03-15T10:30:00Z'
  }
];

export const INITIAL_HELMETS_GEAR: HelmetGearItem[] = [
  {
    id: 'gear-1',
    type: 'helmet',
    sku: 'HLM-SHO-X15-M',
    brand: 'Shoei',
    model: 'X-Fifteen Marquez Motegi 4',
    size: 'M',
    safetyCert: 'FIM & ECE',
    quantityInStock: 2,
    minAlertThreshold: 3,
    costPrice: 620,
    price: 999.99,
    color: 'Red/White/Gold',
    gearType: 'Full Face Helmet',
    location: 'Mantash Flagship Hub (Downtown)',
    createdAt: '2024-02-10T11:00:00Z'
  },
  {
    id: 'gear-2',
    type: 'helmet',
    sku: 'HLM-ARA-RX7V-L',
    brand: 'Arai',
    model: 'Corsair-X / RX-7V EVO Carbon',
    size: 'L',
    safetyCert: 'DOT & ECE',
    quantityInStock: 8,
    minAlertThreshold: 4,
    costPrice: 750,
    price: 1199.95,
    color: 'Matte Raw Carbon',
    gearType: 'Full Face Helmet',
    location: 'Mantash Flagship Hub (Downtown)',
    createdAt: '2024-01-18T10:00:00Z'
  },
  {
    id: 'gear-3',
    type: 'helmet',
    sku: 'HLM-AGV-PISTA-XL',
    brand: 'AGV',
    model: 'Pista GP RR Anno 75 Carbon',
    size: 'XL',
    safetyCert: 'FIM & ECE',
    quantityInStock: 1,
    minAlertThreshold: 2,
    costPrice: 1150,
    price: 1749.95,
    color: 'Gloss Carbon / Metallic Orange',
    gearType: 'Full Face Helmet',
    location: 'Mantash Flagship Hub (Downtown)',
    createdAt: '2024-03-02T13:20:00Z'
  },
  {
    id: 'gear-4',
    type: 'helmet',
    sku: 'JCK-ALP-ATEM-L',
    brand: 'Alpinestars',
    model: 'Atem V4 Tech-Air Leather Jacket',
    size: 'L',
    safetyCert: 'ECE',
    quantityInStock: 6,
    minAlertThreshold: 3,
    costPrice: 480,
    price: 799.95,
    color: 'Black / Flo Orange',
    gearType: 'Riding Jacket',
    location: 'Mantash Flagship Hub (Downtown)',
    createdAt: '2024-02-14T09:40:00Z'
  },
  {
    id: 'gear-5',
    type: 'helmet',
    sku: 'SUT-DAI-MISANO-S',
    brand: 'Dainese',
    model: 'Misano 3 D-Air 1-Piece Pro Suit',
    size: 'S',
    safetyCert: 'ECE',
    quantityInStock: 0,
    minAlertThreshold: 2,
    costPrice: 1850,
    price: 2999.00,
    color: 'Black / Fluo Red',
    gearType: 'Racing Suit',
    location: 'Mantash Flagship Hub (Downtown)',
    createdAt: '2024-01-25T14:00:00Z'
  },
  {
    id: 'gear-6',
    type: 'helmet',
    sku: 'HLM-BEL-RACE-M',
    brand: 'Bell',
    model: 'Race Star Flex DLX',
    size: 'M',
    safetyCert: 'DOT & ECE',
    quantityInStock: 5,
    minAlertThreshold: 3,
    costPrice: 490,
    price: 799.95,
    color: 'Gloss Lux Black',
    gearType: 'Full Face Helmet',
    location: 'Mantash West Coast Outlet',
    createdAt: '2024-02-20T17:15:00Z'
  }
];

export const INITIAL_SPARE_PARTS: SparePartItem[] = [
  {
    id: 'part-1',
    type: 'part',
    partNumber: 'EXH-AKR-S10RR',
    brand: 'Akrapovič',
    name: 'Evolution Line Full Titanium Exhaust System',
    compatibleModels: 'BMW S1000RR (2020-2024)',
    category: 'Exhaust',
    shelfBinLocation: 'Bay 4 - Row B - Bin 12',
    stockCount: 3,
    reorderPoint: 4,
    unitCost: 1950.00,
    unitPrice: 2890.00,
    location: 'Mantash North Service & Warehouse',
    createdAt: '2024-02-01T12:00:00Z'
  },
  {
    id: 'part-2',
    type: 'part',
    partNumber: 'BRK-BRM-GP4MS',
    brand: 'Brembo',
    name: 'GP4-MS CNC Monobloc Radial Brake Calipers (100mm)',
    compatibleModels: 'Ducati Panigale V4, Aprilia RSV4, Yamaha R1',
    category: 'Brakes',
    shelfBinLocation: 'Bay 2 - Row A - Bin 05',
    stockCount: 1,
    reorderPoint: 3,
    unitCost: 2100.00,
    unitPrice: 2995.00,
    location: 'Mantash Flagship Hub (Downtown)',
    createdAt: '2024-02-12T15:30:00Z'
  },
  {
    id: 'part-3',
    type: 'part',
    partNumber: 'PIR-DCR-12070',
    brand: 'Pirelli',
    name: 'Diablo Supercorsa V4 SP Front Tire (120/70ZR17)',
    compatibleModels: 'Universal 17-inch Superbike Fitment',
    category: 'Tires',
    shelfBinLocation: 'Bay 7 - Tire Rack 01',
    stockCount: 14,
    reorderPoint: 6,
    unitCost: 145.00,
    unitPrice: 245.00,
    location: 'Mantash North Service & Warehouse',
    createdAt: '2024-03-05T09:10:00Z'
  },
  {
    id: 'part-4',
    type: 'part',
    partNumber: 'PIR-DCR-20055',
    brand: 'Pirelli',
    name: 'Diablo Supercorsa V4 SP Rear Tire (200/55ZR17)',
    compatibleModels: 'Ducati Panigale, Yamaha R1, BMW S1000RR',
    category: 'Tires',
    shelfBinLocation: 'Bay 7 - Tire Rack 02',
    stockCount: 8,
    reorderPoint: 5,
    unitCost: 210.00,
    unitPrice: 345.00,
    location: 'Mantash North Service & Warehouse',
    createdAt: '2024-03-05T09:15:00Z'
  },
  {
    id: 'part-5',
    type: 'part',
    partNumber: 'MOT-300V-1550',
    brand: 'Motul',
    name: '300V Factory Line 15W50 Synthetic Ester 4L Can',
    compatibleModels: 'High-Performance 4-Stroke Motorcycles',
    category: 'Oil & Fluids',
    shelfBinLocation: 'Bay 1 - Fluids - Bin 08',
    stockCount: 22,
    reorderPoint: 10,
    unitCost: 48.00,
    unitPrice: 79.99,
    location: 'Mantash Flagship Hub (Downtown)',
    createdAt: '2024-03-11T16:00:00Z'
  },
  {
    id: 'part-6',
    type: 'part',
    partNumber: 'ELC-YUA-YTZ10S',
    brand: 'Yuasa',
    name: 'High Performance AGM Sealed Battery (YTZ10S)',
    compatibleModels: 'Yamaha R1/R6, MT-09, Honda CBR600RR',
    category: 'Electrical',
    shelfBinLocation: 'Bay 3 - Electrical - Bin 19',
    stockCount: 4,
    reorderPoint: 5,
    unitCost: 85.00,
    unitPrice: 145.00,
    location: 'Mantash Flagship Hub (Downtown)',
    createdAt: '2024-02-18T14:40:00Z'
  },
  {
    id: 'part-7',
    type: 'part',
    partNumber: 'BRK-SBS-841DC',
    brand: 'SBS Brakes',
    name: 'Dual Carbon Racing Front Brake Pads Set',
    compatibleModels: 'Brembo M50 / Stylema Caliper Systems',
    category: 'Brakes',
    shelfBinLocation: 'Bay 2 - Row B - Bin 02',
    stockCount: 0,
    reorderPoint: 6,
    unitCost: 55.00,
    unitPrice: 94.50,
    location: 'Mantash Flagship Hub (Downtown)',
    createdAt: '2024-01-29T11:20:00Z'
  }
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'act-1',
    action: 'sale',
    title: 'Motorcycle Sold: Harley-Davidson Low Rider S',
    description: 'Chassis #1HD1KEV12PB839102 sold to customer. Title transferred.',
    itemType: 'motorcycle',
    referenceId: '1HD1KEV12PB839102',
    amount: 19490,
    timestamp: '2 hours ago',
    user: 'Alex Mantash'
  },
  {
    id: 'act-2',
    action: 'receive',
    title: 'Received Shipment: Pirelli Diablo Tires (22 units)',
    description: 'Stock updated into Bay 7 racks. Packing slip verified #PS-98124.',
    itemType: 'part',
    referenceId: 'PIR-DCR-12070',
    quantityChange: 22,
    amount: 3910,
    timestamp: '4 hours ago',
    user: 'Carlos M.'
  },
  {
    id: 'act-3',
    action: 'reserve',
    title: 'Reserved: BMW S1000RR M-Package',
    description: 'Deposit paid ($2,000) by customer pending credit approval.',
    itemType: 'motorcycle',
    referenceId: 'WB10E0203P6B88192',
    amount: 21495,
    timestamp: 'Yesterday at 4:30 PM',
    user: 'Sara Vance'
  },
  {
    id: 'act-4',
    action: 'adjustment',
    title: 'Threshold Alert: Shoei X-15 Motegi (2 remaining)',
    description: 'Automatic low-stock threshold trigger sent to procurement.',
    itemType: 'helmet',
    referenceId: 'HLM-SHO-X15-M',
    quantityChange: -1,
    timestamp: 'Yesterday at 11:15 AM',
    user: 'System Bot'
  },
  {
    id: 'act-5',
    action: 'create',
    title: 'New Unit Registered: Ducati Panigale V4 S',
    description: 'Crate unboxed, PDI inspection completed. Added to Showroom floor.',
    itemType: 'motorcycle',
    referenceId: 'JH2SC59038K102941',
    amount: 31995,
    timestamp: '2 days ago',
    user: 'Alex Mantash'
  }
];
