import type { MotorcycleItem, HelmetGearItem, SparePartItem, ActivityLog, StoreLocation } from '../types/inventory';

export const INITIAL_LOCATIONS: StoreLocation[] = [
  {
    id: 'loc-1',
    name: 'Mantash Flagship Hub (Downtown)',
    code: 'MNT-01',
    address: '440 Apex Boulevard, Bay District',
    phone: '+1 (555) 019-8234',
    isPrimary: true
  },
  {
    id: 'loc-2',
    name: 'Mantash North Service & Warehouse',
    code: 'MNT-02',
    address: '128 Industrial Speedway Way',
    phone: '+1 (555) 019-9400'
  },
  {
    id: 'loc-3',
    name: 'Mantash West Coast Outlet',
    code: 'MNT-03',
    address: '89 Coastal Ridge Highway',
    phone: '+1 (555) 019-3321'
  }
];

export const INITIAL_MOTORCYCLES: MotorcycleItem[] = [
  {
    id: 'moto-1',
    type: 'motorcycle',
    vin: 'JH2SC59038K102941',
    brand: 'Ducati',
    model: 'Panigale V4 S',
    year: 2024,
    condition: 'New',
    engineCc: 1103,
    color: 'Rosso Corsa Red',
    mileage: 0,
    costPrice: 26500,
    sellingPrice: 31995,
    status: 'In Stock',
    location: 'Mantash Flagship Hub (Downtown)',
    category: 'Sport',
    createdAt: '2024-03-15T10:30:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'moto-2',
    type: 'motorcycle',
    vin: 'JYARN23E98A019283',
    brand: 'Yamaha',
    model: 'YZF-R1M Carbon',
    year: 2024,
    condition: 'New',
    engineCc: 998,
    color: 'Carbon Fiber / Icon Performance',
    mileage: 0,
    costPrice: 22100,
    sellingPrice: 27599,
    status: 'In Stock',
    location: 'Mantash Flagship Hub (Downtown)',
    category: 'Sport',
    createdAt: '2024-03-10T14:15:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'moto-3',
    type: 'motorcycle',
    vin: 'WB10E0203P6B88192',
    brand: 'BMW',
    model: 'S1000RR M-Package',
    year: 2023,
    condition: 'Used',
    engineCc: 999,
    color: 'M Motorsport Light White',
    mileage: 2840,
    costPrice: 17400,
    sellingPrice: 21495,
    status: 'Reserved',
    location: 'Mantash North Service & Warehouse',
    category: 'Sport',
    createdAt: '2024-02-28T09:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1609630875171-b1321377ee65?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'moto-4',
    type: 'motorcycle',
    vin: 'JKAZX2E17MA039182',
    brand: 'Kawasaki',
    model: 'Ninja ZX-10R KRT',
    year: 2024,
    condition: 'New',
    engineCc: 998,
    color: 'Lime Green / Ebony',
    mileage: 0,
    costPrice: 15300,
    sellingPrice: 18699,
    status: 'In Stock',
    location: 'Mantash Flagship Hub (Downtown)',
    category: 'Sport',
    createdAt: '2024-03-01T11:20:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1599819811279-d5ad9cccf838?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'moto-5',
    type: 'motorcycle',
    vin: 'VBKMX9408PM381920',
    brand: 'KTM',
    model: '1290 Super Duke R Evo',
    year: 2023,
    condition: 'Used',
    engineCc: 1301,
    color: 'Factory Orange / Stealth Black',
    mileage: 4120,
    costPrice: 14800,
    sellingPrice: 18250,
    status: 'In Stock',
    location: 'Mantash Flagship Hub (Downtown)',
    category: 'Naked',
    createdAt: '2024-01-20T16:45:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1571188654248-7a89213915f7?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'moto-6',
    type: 'motorcycle',
    vin: 'SMTT33418RN982144',
    brand: 'Triumph',
    model: 'Street Triple 765 RS',
    year: 2024,
    condition: 'New',
    engineCc: 765,
    color: 'Carnival Red',
    mileage: 0,
    costPrice: 10400,
    sellingPrice: 12795,
    status: 'In Stock',
    location: 'Mantash West Coast Outlet',
    category: 'Naked',
    createdAt: '2024-03-12T13:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'moto-7',
    type: 'motorcycle',
    vin: '1HD1KEV12PB839102',
    brand: 'Harley-Davidson',
    model: 'Low Rider S (FXLRS)',
    year: 2023,
    condition: 'Used',
    engineCc: 1923,
    color: 'Vivid Black Dark Finish',
    mileage: 5600,
    costPrice: 15200,
    sellingPrice: 19490,
    status: 'Sold',
    location: 'Mantash Flagship Hub (Downtown)',
    category: 'Cruiser',
    createdAt: '2024-01-11T15:10:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1558980664-3a031cf67ea8?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'moto-8',
    type: 'motorcycle',
    vin: 'JH2RC7909KK829103',
    brand: 'Honda',
    model: 'Africa Twin Adventure Sports ES',
    year: 2024,
    condition: 'New',
    engineCc: 1084,
    color: 'Pearl Glare White Tricolor',
    mileage: 0,
    costPrice: 14700,
    sellingPrice: 18399,
    status: 'In Stock',
    location: 'Mantash Flagship Hub (Downtown)',
    category: 'Adventure',
    createdAt: '2024-03-08T08:30:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1591637333184-19aa84b3e01f?auto=format&fit=crop&w=600&q=80'
  }
];

export const INITIAL_HELMETS_GEAR: HelmetGearItem[] = [
  {
    id: 'gear-1',
    type: 'helmet',
    sku: 'HLM-SHO-X15-M',
    brand: 'Shoei',
    model: 'X-Fifteen Marquez Motegi 4',
    size: 'M',
    safetyCert: 'FIM & ECE',
    quantityInStock: 2, // Low stock alert! (threshold is 3)
    minAlertThreshold: 3,
    costPrice: 620,
    price: 999.99,
    color: 'Red/White/Gold',
    gearType: 'Full Face Helmet',
    location: 'Mantash Flagship Hub (Downtown)',
    createdAt: '2024-02-10T11:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1558981852-426c6c22a060?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'gear-2',
    type: 'helmet',
    sku: 'HLM-ARA-RX7V-L',
    brand: 'Arai',
    model: 'Corsair-X / RX-7V EVO Carbon',
    size: 'L',
    safetyCert: 'DOT & ECE',
    quantityInStock: 8,
    minAlertThreshold: 4,
    costPrice: 750,
    price: 1199.95,
    color: 'Matte Raw Carbon',
    gearType: 'Full Face Helmet',
    location: 'Mantash Flagship Hub (Downtown)',
    createdAt: '2024-01-18T10:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1558980394-4c7c9299fe96?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'gear-3',
    type: 'helmet',
    sku: 'HLM-AGV-PISTA-XL',
    brand: 'AGV',
    model: 'Pista GP RR Anno 75 Carbon',
    size: 'XL',
    safetyCert: 'FIM & ECE',
    quantityInStock: 1, // Critical low stock
    minAlertThreshold: 2,
    costPrice: 1150,
    price: 1749.95,
    color: 'Gloss Carbon / Metallic Orange',
    gearType: 'Full Face Helmet',
    location: 'Mantash Flagship Hub (Downtown)',
    createdAt: '2024-03-02T13:20:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1558981420-87aa9dad1c89?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'gear-4',
    type: 'helmet',
    sku: 'JCK-ALP-ATEM-L',
    brand: 'Alpinestars',
    model: 'Atem V4 Tech-Air Leather Jacket',
    size: 'L',
    safetyCert: 'ECE',
    quantityInStock: 6,
    minAlertThreshold: 3,
    costPrice: 480,
    price: 799.95,
    color: 'Black / Flo Orange',
    gearType: 'Riding Jacket',
    location: 'Mantash Flagship Hub (Downtown)',
    createdAt: '2024-02-14T09:40:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'gear-5',
    type: 'helmet',
    sku: 'SUT-DAI-MISANO-S',
    brand: 'Dainese',
    model: 'Misano 3 D-Air 1-Piece Pro Suit',
    size: 'S',
    safetyCert: 'ECE',
    quantityInStock: 0, // Out of stock!
    minAlertThreshold: 2,
    costPrice: 1850,
    price: 2999.00,
    color: 'Black / Fluo Red',
    gearType: 'Racing Suit',
    location: 'Mantash Flagship Hub (Downtown)',
    createdAt: '2024-01-25T14:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'gear-6',
    type: 'helmet',
    sku: 'HLM-BEL-RACE-M',
    brand: 'Bell',
    model: 'Race Star Flex DLX',
    size: 'M',
    safetyCert: 'DOT & ECE',
    quantityInStock: 5,
    minAlertThreshold: 3,
    costPrice: 490,
    price: 799.95,
    color: 'Gloss Lux Black',
    gearType: 'Full Face Helmet',
    location: 'Mantash West Coast Outlet',
    createdAt: '2024-02-20T17:15:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1558981852-426c6c22a060?auto=format&fit=crop&w=600&q=80'
  }
];

export const INITIAL_SPARE_PARTS: SparePartItem[] = [
  {
    id: 'part-1',
    type: 'part',
    partNumber: 'EXH-AKR-S10RR',
    brand: 'Akrapovič',
    name: 'Evolution Line Full Titanium Exhaust System',
    compatibleModels: 'BMW S1000RR (2020-2024)',
    category: 'Exhaust',
    shelfBinLocation: 'Bay 4 - Row B - Bin 12',
    stockCount: 3, // Low stock (reorder is 4)
    reorderPoint: 4,
    unitCost: 1950.00,
    unitPrice: 2890.00,
    location: 'Mantash North Service & Warehouse',
    createdAt: '2024-02-01T12:00:00Z'
  },
  {
    id: 'part-2',
    type: 'part',
    partNumber: 'BRK-BRM-GP4MS',
    brand: 'Brembo',
    name: 'GP4-MS CNC Monobloc Radial Brake Calipers (100mm)',
    compatibleModels: 'Ducati Panigale V4, Aprilia RSV4, Yamaha R1',
    category: 'Brakes',
    shelfBinLocation: 'Bay 2 - Row A - Bin 05',
    stockCount: 1, // Critical low stock
    reorderPoint: 3,
    unitCost: 2100.00,
    unitPrice: 2995.00,
    location: 'Mantash Flagship Hub (Downtown)',
    createdAt: '2024-02-12T15:30:00Z'
  },
  {
    id: 'part-3',
    type: 'part',
    partNumber: 'PIR-DCR-12070',
    brand: 'Pirelli',
    name: 'Diablo Supercorsa V4 SP Front Tire (120/70ZR17)',
    compatibleModels: 'Universal 17-inch Superbike Fitment',
    category: 'Tires',
    shelfBinLocation: 'Bay 7 - Tire Rack 01',
    stockCount: 14,
    reorderPoint: 6,
    unitCost: 145.00,
    unitPrice: 245.00,
    location: 'Mantash North Service & Warehouse',
    createdAt: '2024-03-05T09:10:00Z'
  },
  {
    id: 'part-4',
    type: 'part',
    partNumber: 'PIR-DCR-20055',
    brand: 'Pirelli',
    name: 'Diablo Supercorsa V4 SP Rear Tire (200/55ZR17)',
    compatibleModels: 'Ducati Panigale, Yamaha R1, BMW S1000RR',
    category: 'Tires',
    shelfBinLocation: 'Bay 7 - Tire Rack 02',
    stockCount: 8,
    reorderPoint: 5,
    unitCost: 210.00,
    unitPrice: 345.00,
    location: 'Mantash North Service & Warehouse',
    createdAt: '2024-03-05T09:15:00Z'
  },
  {
    id: 'part-5',
    type: 'part',
    partNumber: 'MOT-300V-1550',
    brand: 'Motul',
    name: '300V Factory Line 15W50 Synthetic Ester 4L Can',
    compatibleModels: 'High-Performance 4-Stroke Motorcycles',
    category: 'Oil & Fluids',
    shelfBinLocation: 'Bay 1 - Fluids - Bin 08',
    stockCount: 22,
    reorderPoint: 10,
    unitCost: 48.00,
    unitPrice: 79.99,
    location: 'Mantash Flagship Hub (Downtown)',
    createdAt: '2024-03-11T16:00:00Z'
  },
  {
    id: 'part-6',
    type: 'part',
    partNumber: 'ELC-YUA-YTZ10S',
    brand: 'Yuasa',
    name: 'High Performance AGM Sealed Battery (YTZ10S)',
    compatibleModels: 'Yamaha R1/R6, MT-09, Honda CBR600RR',
    category: 'Electrical',
    shelfBinLocation: 'Bay 3 - Electrical - Bin 19',
    stockCount: 4,
    reorderPoint: 5,
    unitCost: 85.00,
    unitPrice: 145.00,
    location: 'Mantash Flagship Hub (Downtown)',
    createdAt: '2024-02-18T14:40:00Z'
  },
  {
    id: 'part-7',
    type: 'part',
    partNumber: 'BRK-SBS-841DC',
    brand: 'SBS Brakes',
    name: 'Dual Carbon Racing Front Brake Pads Set',
    compatibleModels: 'Brembo M50 / Stylema Caliper Systems',
    category: 'Brakes',
    shelfBinLocation: 'Bay 2 - Row B - Bin 02',
    stockCount: 0, // Out of stock!
    reorderPoint: 6,
    unitCost: 55.00,
    unitPrice: 94.50,
    location: 'Mantash Flagship Hub (Downtown)',
    createdAt: '2024-01-29T11:20:00Z'
  }
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'act-1',
    action: 'sale',
    title: 'Motorcycle Sold: Harley-Davidson Low Rider S',
    description: 'Chassis #1HD1KEV12PB839102 sold to customer. Title transferred.',
    itemType: 'motorcycle',
    referenceId: '1HD1KEV12PB839102',
    amount: 19490,
    timestamp: '2 hours ago',
    user: 'Alex Mantash'
  },
  {
    id: 'act-2',
    action: 'receive',
    title: 'Received Shipment: Pirelli Diablo Tires (22 units)',
    description: 'Stock updated into Bay 7 racks. Packing slip verified #PS-98124.',
    itemType: 'part',
    referenceId: 'PIR-DCR-12070',
    quantityChange: 22,
    amount: 3910,
    timestamp: '4 hours ago',
    user: 'Carlos M.'
  },
  {
    id: 'act-3',
    action: 'reserve',
    title: 'Reserved: BMW S1000RR M-Package',
    description: 'Deposit paid ($2,000) by customer pending credit approval.',
    itemType: 'motorcycle',
    referenceId: 'WB10E0203P6B88192',
    amount: 21495,
    timestamp: 'Yesterday at 4:30 PM',
    user: 'Sara Vance'
  },
  {
    id: 'act-4',
    action: 'adjustment',
    title: 'Threshold Alert: Shoei X-15 Motegi (2 remaining)',
    description: 'Automatic low-stock threshold trigger sent to procurement.',
    itemType: 'helmet',
    referenceId: 'HLM-SHO-X15-M',
    quantityChange: -1,
    timestamp: 'Yesterday at 11:15 AM',
    user: 'System Bot'
  },
  {
    id: 'act-5',
    action: 'create',
    title: 'New Unit Registered: Ducati Panigale V4 S',
    description: 'Crate unboxed, PDI inspection completed. Added to Showroom floor.',
    itemType: 'motorcycle',
    referenceId: 'JH2SC59038K102941',
    amount: 31995,
    timestamp: '2 days ago',
    user: 'Alex Mantash'
  }
];
